
(use-trait ft-trait .trait-sip-010.sip-010-trait)

;; helper functions:

(define-private (get-staker-at-cycle-or-default-by-tx-sender (reward-cycle uint) (staked-token-trait <ft-trait>))
  (contract-call? .alex-reserve-pool get-staker-at-cycle-or-default staked-token-trait reward-cycle (default-to u0 (contract-call? .alex-reserve-pool get-user-id staked-token-trait tx-sender)))
)

(define-private (get-staking-reward-by-tx-sender (target-cycle uint) (staked-token-trait <ft-trait>))
  (contract-call? .alex-reserve-pool get-staking-reward staked-token-trait (default-to u0 (contract-call? .alex-reserve-pool get-user-id staked-token-trait tx-sender)) target-cycle)
)

(define-read-only (get-staked (staked-token-trait <ft-trait>) (reward-cycles (list 2000 uint)))
  (map 
    get-staker-at-cycle-or-default-by-tx-sender 
    reward-cycles
    (list 
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait )
  )
)

(define-read-only (get-staking-rewards (staked-token-trait <ft-trait>) (reward-cycles (list 2000 uint)))
  (map 
    get-staking-reward-by-tx-sender 
    reward-cycles
(list 
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait
staked-token-trait )      
  )
)